# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customers.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtWidgets, uic, QtCore
from login import Ui_Login
from PyQt5.QtWidgets import QAction


class Ui_Customers(object):
    def setupUi(self, Customers):
        Customers.setObjectName("Customers")
        Customers.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Customers)
        self.centralwidget.setObjectName("centralwidget")
        Customers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Customers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Customers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Customers)
        self.statusbar.setObjectName("statusbar")
        Customers.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Customers)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(Customers)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        

        self.retranslateUi(Customers)
        QtCore.QMetaObject.connectSlotsByName(Customers)

    def retranslateUi(self, Customers):
        _translate = QtCore.QCoreApplication.translate
        Customers.setWindowTitle(_translate("Customers", "Customers"))
        self.menuFile.setTitle(_translate("Customers", "App"))
        self.actionOpen.setText(_translate("Customers", "Login"))
        self.actionClose.setText(_translate("Customers", "Close"))
        self.actionOpen.triggered.connect(self.actionOpenLogin)

    def actionOpenLogin(self):
        self.window_login = QtWidgets.QDialog()
        self.ui = Ui_Login()
        self.ui.setupUi(self.window_login)
        self.window_login.show()  
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Customers = QtWidgets.QMainWindow()
    ui = Ui_Customers()
    ui.setupUi(Customers)
    Customers.show()
    sys.exit(app.exec_())
